"""
Esmerald settings for expensetracker project.

Generated by 'esmerald createproject' using Esmerald 2.0.3.
"""

from typing import Optional, Tuple
from functools import cached_property

from esmerald.conf.enums import EnvironmentType
from esmerald.config.jwt import JWTConfig
from saffier import Database, Registry

from ..settings import AppSettings


class DevelopmentAppSettings(AppSettings):
    debug: bool = True
    app_name: str = "Expense Tracker (Dev)"
    title: str = "Expense Tracker (Dev)"
    environment: Optional[str] = EnvironmentType.DEVELOPMENT
    secret_key: str = "^6l*+s7n!:qbbPXjkS?sbJCFZ%R(I:"

    @property
    def jwt_config(self) -> JWTConfig:
        """
        A JWT object configuration to be passed to the application middleware
        """
        return JWTConfig(
            signing_key=self.secret_key,
            auth_header_types=["Bearer", "Token"]
        )

    @cached_property
    def db_access(self) -> Tuple[Database, Registry]:
        db = Database(
            config={"connection": {
                "credentials": { 
                    "scheme": "postgresql",
                    "host": "localhost",
                    "port": "5432",
                    "user": "expensesusr",
                    "password": "67225BBB",
                    "database": "expensesdb"
                }
            }
        })
        return db, Registry(db)

    # @cached_property
    # def openapi_config(self) -> OpenAPIConfig:
    #     return OpenAPIConfig(
    #         title=self.title,
    #         docs_url="/docs/swagger"
    #     )