"""
Generated by 'esmerald createapp' using Esmerald 2.0.3.
"""
from pydantic import BaseModel
from typing import Optional


class ErrorSchema(BaseModel):
    detail: str


class UserCreateSchema(BaseModel):
    """
    User creation schema
    """
    username: str
    password: str
    first_name: str
    last_name: str
    email: str


class UserUpdatechema(BaseModel):
    """
    User update schema
    """
    password: Optional[str]
    first_name: Optional[str]
    last_name: Optional[str]


class UserOutSchema(BaseModel):
    """
    User detail schema
    """
    id: int
    username: str
    first_name: str
    last_name: str
