"""
Generated by 'esmerald createapp' using Esmerald 2.0.3.
"""
from typing import Optional
from datetime import datetime
from pydantic import BaseModel, field_serializer
from expensetracker.apps.base_enum import TrxType


class ErrorSchema(BaseModel):
    """
    Error schema
    """
    detail: str

class TransactionCreateSchema(BaseModel):
    """
    Transaction creation schema
    """
    trx_type: str
    amount: float
    currency: str
    trx_date: datetime
    category: Optional[int]
    notes: Optional[str]


class TransactionUpdateSchema(BaseModel):
    """
    Transaction update schema
    """
    trx_type: Optional[str] = None
    amount: Optional[float] = None
    currency: Optional[str] = None
    trx_date: Optional[datetime] = None
    category: Optional[int] = None
    notes: Optional[str] = None


class TransactionOutListSchema(BaseModel):
    """
    Transaction list output schema
    """
    id: int
    trx_type: str
    amount: float
    currency: str


class TransactionOutDetailSchema(BaseModel):
    """
    Transaction detailed output schema
    """
    id: int
    trx_type: str
    amount: float
    currency: str
    trx_date: str
    user: int
    category: Optional[int]
    notes: Optional[str]
