"""
Generated by 'esmerald createapp' using Esmerald 2.0.3.
"""
from pydantic import BaseModel

from expensetracker.apps.base_enum import TrxType


class ErrorSchema(BaseModel):
    """
    Error schema
    """
    detail: str


class CategoryCreateSchema(BaseModel):
    """
    Category creation schema
    """
    description: str
    cat_type: str


class CategoryUpdateSchema(BaseModel):
    """
    Category update schema
    """
    description: str


class CategoryOutSchema(BaseModel):
    """
    Category output schema
    """
    id: int
    description: str
    cat_type: str
