"""
Generated by 'esmerald createapp' using Esmerald 2.0.3.
"""
from pydantic import BaseModel
from typing import Optional


class ErrorSchema(BaseModel):
    detail: str


class LoginSchema(BaseModel):
    """
    Login schema
    """
    username: str
    password: str
