"""
Esmerald settings for expensetracker project.

Generated by 'esmerald createproject' using Esmerald 2.0.3.
"""

from typing import Optional

from esmerald.conf.enums import EnvironmentType
from esmerald.conf.global_settings import EsmeraldAPISettings


class AppSettings(EsmeraldAPISettings):
    app_name: str = "Expense Tracker"
    title: str = "Expense Tracker"
    environment: Optional[str] = EnvironmentType.PRODUCTION