"""
Esmerald settings for expensetracker project.

Generated by 'esmerald createproject' using Esmerald 2.0.3.
"""

from typing import Optional

from esmerald.conf.enums import EnvironmentType

from ..settings import AppSettings


class TestingAppSettings(AppSettings):
    debug: bool = True
    app_name: str = "Expense Tracker (QA)"
    title: str = "Expense Tracker (QA)"
    environment: Optional[str] = EnvironmentType.TESTING